# Generated by Django 6.0 on 2026-02-03 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commisions', to='dashboard.priceconfig')),
            ],
        ),
    ]
