# Generated by Django 6.0 on 2026-06-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_marketing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marketing_images/'),
        ),
    ]
