# Generated by Django 6.0 on 2026-02-03 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_commision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commision',
            name='price_config',
        ),
    ]
