services:
  db:
    image: postgis/postgis:15-3.3
    container_name: ober_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5431:5432"

  redis:
    image: redis:7-alpine
    container_name: ober_redis
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    container_name: ober_backend
    command: daphne -b 0.0.0.0 -p 9700 src._config.asgi:application
    volumes:
      - .:/app 
      - media_data:/app/media
      - static_data:/app/static
    env_file:
      - .env
    depends_on:
      - db
      - redis
    environment:
      GDAL_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/libgdal.so
      GEOS_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/libgeos_c.so


  worker:
    build: .
    container_name: ober_worker
    command: celery -A src._config worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: ober_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - media_data:/app/media:ro
      - static_data:/app/static:ro
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  media_data:
  static_data:
  redis_data: