services:
  db:
    image: postgis/postgis:15-3.3
    container_name: ober_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_EXTERNAL_PORT:-5431}:${POSTGRES_PORT}"
    networks:
      - ober_network

  redis:
    image: redis:7-alpine
    container_name: ober_redis
    command: redis-server --port ${REDIS_PORT}
    ports:
      - "${REDIS_EXTERNAL_PORT:-6378}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    networks:
      - ober_network

  backend:
    build: .
    container_name: ober_backend
    command: daphne -b 0.0.0.0 -p 8000 src._config.asgi:application
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - kyc_service
    environment:
      GDAL_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/libgdal.so
      GEOS_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/libgeos_c.so
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      REDIS_URL: ${REDIS_LOCATION}
      KYC_SERVICE_URL: http://kyc_service:8000/verify-identity/
    ports:
      - "9500:8000"
    networks:
      - ober_network

  kyc_service:
    build: ./kyc_service
    container_name: ober_kyc
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./kyc_service:/app
    ports:
      - "8001:8000"
    networks:
      - ober_network

  worker:
    build: .
    container_name: ober_worker
    command: celery -A src._config worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      REDIS_URL: ${REDIS_LOCATION}
    networks:
      - ober_network

volumes:
  postgres_data:
  redis_data:

networks:
  ober_network:
    driver: bridge
