version: "3.8"

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5431:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    command: gunicorn src._config.wsgi:application --bind 0.0.0.0:9700
    volumes:
      - .:/app 
      - media_data:/app/media
    ports:
      - "9700:9700"
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  media_data:
  redis_data:
