# Generated by Django 6.0 on 2026-01-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RideReview',
        ),
    ]
