# Generated by Django 6.0 on 2026-01-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0002_ride_payment_method_riderequest_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='payment_method',
        ),
    ]
