# Generated by Django 6.0 on 2026-02-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0004_ride_cancellation_fee_ride_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='drop_off_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]