# Generated by Django 6.0 on 2026-02-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0005_ride_arrival_time_ride_drop_off_time_ride_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card')], default='CASH', max_length=10),
        ),
    ]