# Generated by Django 6.0 on 2026-01-14 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDriverUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_photo', models.ImageField(blank=True, null=True, upload_to='drivers/pending/photos/')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('nid_front', models.ImageField(blank=True, null=True, upload_to='drivers/pending/nid/')),
                ('nid_back', models.ImageField(blank=True, null=True, upload_to='drivers/pending/nid/')),
                ('license_front', models.ImageField(blank=True, null=True, upload_to='drivers/pending/license/')),
                ('license_back', models.ImageField(blank=True, null=True, upload_to='drivers/pending/license/')),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_photo', models.ImageField(blank=True, null=True, upload_to='drivers/pending/vehicle/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_update', to='accounts.driverprofile')),
            ],
        ),
    ]
