# Generated by Django 6.0 on 2026-01-17 06:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pendingdriverupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='last_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle_plate',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
