# Generated by Django 6.0 on 2026-01-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
