# Generated by Django 6.0 on 2026-01-31 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_driverprofile_created_at_driverprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
