# Generated by Django 6.0 on 2026-02-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_driverprofile_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='admin/photos/'),
        ),
    ]
