# Generated by Django 6.0 on 2026-02-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='is_blocked',
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
