# Generated by Django 6.0 on 2026-02-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_driverprofile_is_blocked_user_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='driver_license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='nid_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pendingdriverupdate',
            name='driver_license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pendingdriverupdate',
            name='nid_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
