# Generated by Django 6.0 on 2026-02-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_driverprofile_driver_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
